language: haskell

cache:
  directories:
    - $HOME/.cabal/packages
    - $HOME/.cabal/store
    - $HOME/.cabal/bin
    - $HOME/.stack/bin
    - $HOME/.stack/precompiled
    - $HOME/.stack/programs
    - $HOME/.stack/setup-exe-cache
    - $HOME/.stack/snapshots

ghc: 
    - 7.8

install:
    - cabal update
    - cabal install hakyll

script:
    - ghc site.hs
    - ./site build
