name: Publish

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: | 
          sudo apt install -y ghc libghc-hakyll-dev 
      - name: Build gh-pages
        run: | 
          ghc site.hs
          ./site build
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: Move assets to gh-pages branch
        run: |
          cp -r _site/* ./gh-pages
      - name: Set git config
        run: |
          cd gh-pages
          git config --local user.email ugwis@users.noreply.github.com
          git config --local user.name Yuta Kitamura
          git config pull.rebase false
      - name: Commit and Push
        run: |
          cd gh-pages
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -am "Commit by GitHub Actions (triggered by ${GITHUB_SHA})"
          git pull --prune
          git push origin gh-pages
